"""add card instance playmat fields

Revision ID: 2a4a777a3f96
Revises: 38fe89b1d3cc
Create Date: 2026-04-22 05:54:59.502657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a4a777a3f96'
down_revision = '38fe89b1d3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archetypes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tagsJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgAnalysis'
    )
    with op.batch_alter_table('archetypes', schema='mtgAnalysis') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_archetypes_name'), ['name'], unique=True)

    op.create_table('cards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.Column('oracleId', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalizedName', sa.Text(), nullable=True),
    sa.Column('faceName', sa.Text(), nullable=True),
    sa.Column('manaCost', sa.Text(), nullable=True),
    sa.Column('manaValue', sa.Numeric(), nullable=True),
    sa.Column('colors', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('colorIdentity', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('typeLine', sa.Text(), nullable=True),
    sa.Column('oracleText', sa.Text(), nullable=True),
    sa.Column('power', sa.Text(), nullable=True),
    sa.Column('toughness', sa.Text(), nullable=True),
    sa.Column('loyalty', sa.Text(), nullable=True),
    sa.Column('defense', sa.Text(), nullable=True),
    sa.Column('layout', sa.Text(), nullable=True),
    sa.Column('side', sa.Text(), nullable=True),
    sa.Column('isToken', sa.Boolean(), nullable=True),
    sa.Column('isReserved', sa.Boolean(), nullable=True),
    sa.Column('isReprint', sa.Boolean(), nullable=True),
    sa.Column('edhrecRank', sa.Integer(), nullable=True),
    sa.Column('defaultSetCode', sa.Text(), nullable=True),
    sa.Column('defaultSetName', sa.Text(), nullable=True),
    sa.Column('rarity', sa.Text(), nullable=True),
    sa.Column('availability', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('legalities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rawJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgCore'
    )
    with op.batch_alter_table('cards', schema='mtgCore') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgCore_cards_defaultSetCode'), ['defaultSetCode'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_cards_manaValue'), ['manaValue'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_cards_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_cards_normalizedName'), ['normalizedName'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_cards_oracleId'), ['oracleId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_cards_uuid'), ['uuid'], unique=True)

    op.create_table('sets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('releaseDate', sa.Date(), nullable=True),
    sa.Column('block', sa.Text(), nullable=True),
    sa.Column('setType', sa.Text(), nullable=True),
    sa.Column('isDigital', sa.Boolean(), nullable=True),
    sa.Column('totalCards', sa.Integer(), nullable=True),
    sa.Column('tokenCount', sa.Integer(), nullable=True),
    sa.Column('rawJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgCore'
    )
    with op.batch_alter_table('sets', schema='mtgCore') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgCore_sets_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_mtgCore_sets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_sets_setType'), ['setType'], unique=False)

    op.create_table('gamePlayers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gameId', sa.BigInteger(), nullable=False),
    sa.Column('seatNumber', sa.Integer(), nullable=False),
    sa.Column('playerType', sa.Text(), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=True),
    sa.Column('aiProfile', sa.Text(), nullable=True),
    sa.Column('deckId', sa.BigInteger(), nullable=True),
    sa.Column('deckVersionId', sa.BigInteger(), nullable=True),
    sa.Column('startingLife', sa.Integer(), nullable=True),
    sa.Column('startingHandSize', sa.Integer(), nullable=True),
    sa.Column('finalPlacement', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('commanderCastCount', sa.Integer(), nullable=True),
    sa.Column('commanderDamageDealt', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deckId'], ['mtgDecks.decks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deckVersionId'], ['mtgDecks.deckVersions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gameId'], ['mtgGames.games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gameId', 'seatNumber', name='uq_gamePlayers_game_seat'),
    schema='mtgGames'
    )
    with op.batch_alter_table('gamePlayers', schema='mtgGames') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgGames_gamePlayers_aiProfile'), ['aiProfile'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_gamePlayers_deckId'), ['deckId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_gamePlayers_deckVersionId'), ['deckVersionId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_gamePlayers_gameId'), ['gameId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_gamePlayers_playerType'), ['playerType'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_gamePlayers_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_gamePlayers_userId'), ['userId'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parentGameId', sa.BigInteger(), nullable=True),
    sa.Column('parentSnapshotId', sa.BigInteger(), nullable=True),
    sa.Column('branchedFromSequence', sa.BigInteger(), nullable=True),
    sa.Column('rootGameId', sa.BigInteger(), nullable=True),
    sa.Column('gameMode', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('rngSeed', sa.Text(), nullable=True),
    sa.Column('engineVersion', sa.Text(), nullable=True),
    sa.Column('rulesVersion', sa.Text(), nullable=True),
    sa.Column('startedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('endedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winnerGamePlayerId', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parentGameId'], ['mtgGames.games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parentSnapshotId'], ['mtgGames.stateSnapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winnerGamePlayerId'], ['mtgGames.gamePlayers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgGames'
    )
    with op.batch_alter_table('games', schema='mtgGames') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgGames_games_format'), ['format'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_games_gameMode'), ['gameMode'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_games_parentGameId'), ['parentGameId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_games_parentSnapshotId'), ['parentSnapshotId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_games_rootGameId'), ['rootGameId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_games_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_games_winnerGamePlayerId'), ['winnerGamePlayerId'], unique=False)

    op.create_table('stateSnapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gameId', sa.BigInteger(), nullable=False),
    sa.Column('sequenceNumber', sa.BigInteger(), nullable=False),
    sa.Column('turnNumber', sa.Integer(), nullable=True),
    sa.Column('phase', sa.Text(), nullable=True),
    sa.Column('stateJson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshotHash', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gameId'], ['mtgGames.games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgGames'
    )
    with op.batch_alter_table('stateSnapshots', schema='mtgGames') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgGames_stateSnapshots_gameId'), ['gameId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_stateSnapshots_phase'), ['phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_stateSnapshots_snapshotHash'), ['snapshotHash'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_stateSnapshots_turnNumber'), ['turnNumber'], unique=False)
        batch_op.create_index('ix_stateSnapshots_gameId_sequenceNumber', ['gameId', 'sequenceNumber'], unique=False)

    op.create_table('cardMatchupTags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cardId', sa.BigInteger(), nullable=False),
    sa.Column('relationType', sa.Text(), nullable=False),
    sa.Column('targetTag', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cardId'], ['mtgCore.cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgAnalysis'
    )
    with op.batch_alter_table('cardMatchupTags', schema='mtgAnalysis') as batch_op:
        batch_op.create_index('ix_cardMatchupTags_cardId_relationType_targetTag', ['cardId', 'relationType', 'targetTag'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_cardMatchupTags_cardId'), ['cardId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_cardMatchupTags_relationType'), ['relationType'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_cardMatchupTags_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_cardMatchupTags_targetTag'), ['targetTag'], unique=False)

    op.create_table('cardRoleTags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cardId', sa.BigInteger(), nullable=False),
    sa.Column('roleType', sa.Text(), nullable=False),
    sa.Column('roleValue', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cardId'], ['mtgCore.cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgAnalysis'
    )
    with op.batch_alter_table('cardRoleTags', schema='mtgAnalysis') as batch_op:
        batch_op.create_index('ix_cardRoleTags_cardId_roleType_roleValue', ['cardId', 'roleType', 'roleValue'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_cardRoleTags_cardId'), ['cardId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_cardRoleTags_roleType'), ['roleType'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_cardRoleTags_roleValue'), ['roleValue'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_cardRoleTags_source'), ['source'], unique=False)

    op.create_table('cardFaces',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cardId', sa.BigInteger(), nullable=False),
    sa.Column('faceOrder', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('manaCost', sa.Text(), nullable=True),
    sa.Column('typeLine', sa.Text(), nullable=True),
    sa.Column('oracleText', sa.Text(), nullable=True),
    sa.Column('power', sa.Text(), nullable=True),
    sa.Column('toughness', sa.Text(), nullable=True),
    sa.Column('loyalty', sa.Text(), nullable=True),
    sa.Column('defense', sa.Text(), nullable=True),
    sa.Column('colors', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rawJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['cardId'], ['mtgCore.cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgCore'
    )
    with op.batch_alter_table('cardFaces', schema='mtgCore') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgCore_cardFaces_cardId'), ['cardId'], unique=False)

    op.create_table('printings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cardId', sa.BigInteger(), nullable=False),
    sa.Column('setId', sa.BigInteger(), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.Column('collectorNumber', sa.Text(), nullable=True),
    sa.Column('rarity', sa.Text(), nullable=True),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('flavorText', sa.Text(), nullable=True),
    sa.Column('frameVersion', sa.Text(), nullable=True),
    sa.Column('borderColor', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('isPromo', sa.Boolean(), nullable=True),
    sa.Column('isFullArt', sa.Boolean(), nullable=True),
    sa.Column('availability', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rawJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cardId'], ['mtgCore.cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setId'], ['mtgCore.sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgCore'
    )
    with op.batch_alter_table('printings', schema='mtgCore') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgCore_printings_cardId'), ['cardId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_printings_rarity'), ['rarity'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_printings_setId'), ['setId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_printings_uuid'), ['uuid'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('productCode', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('productType', sa.Text(), nullable=True),
    sa.Column('setId', sa.BigInteger(), nullable=True),
    sa.Column('releaseDate', sa.Date(), nullable=True),
    sa.Column('rawJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['setId'], ['mtgCore.sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgCore'
    )
    with op.batch_alter_table('products', schema='mtgCore') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgCore_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_products_productCode'), ['productCode'], unique=True)
        batch_op.create_index(batch_op.f('ix_mtgCore_products_productType'), ['productType'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_products_setId'), ['setId'], unique=False)

    op.create_table('branches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parentGameId', sa.BigInteger(), nullable=False),
    sa.Column('childGameId', sa.BigInteger(), nullable=False),
    sa.Column('parentSnapshotId', sa.BigInteger(), nullable=True),
    sa.Column('branchLabel', sa.Text(), nullable=True),
    sa.Column('branchReason', sa.Text(), nullable=True),
    sa.Column('createdByUserId', sa.BigInteger(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['childGameId'], ['mtgGames.games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parentGameId'], ['mtgGames.games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parentSnapshotId'], ['mtgGames.stateSnapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgGames'
    )
    with op.batch_alter_table('branches', schema='mtgGames') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgGames_branches_childGameId'), ['childGameId'], unique=True)
        batch_op.create_index(batch_op.f('ix_mtgGames_branches_createdByUserId'), ['createdByUserId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_branches_parentGameId'), ['parentGameId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_branches_parentSnapshotId'), ['parentSnapshotId'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gameId', sa.BigInteger(), nullable=False),
    sa.Column('sequenceNumber', sa.BigInteger(), nullable=False),
    sa.Column('turnNumber', sa.Integer(), nullable=True),
    sa.Column('phase', sa.Text(), nullable=True),
    sa.Column('step', sa.Text(), nullable=True),
    sa.Column('actingGamePlayerId', sa.BigInteger(), nullable=True),
    sa.Column('eventType', sa.Text(), nullable=False),
    sa.Column('visibilityScope', sa.Text(), nullable=True),
    sa.Column('payloadJson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('publicText', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actingGamePlayerId'], ['mtgGames.gamePlayers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gameId'], ['mtgGames.games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gameId', 'sequenceNumber', name='uq_events_game_sequence'),
    schema='mtgGames'
    )
    with op.batch_alter_table('events', schema='mtgGames') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgGames_events_actingGamePlayerId'), ['actingGamePlayerId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_events_eventType'), ['eventType'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_events_gameId'), ['gameId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_events_phase'), ['phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_events_step'), ['step'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_events_turnNumber'), ['turnNumber'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_events_visibilityScope'), ['visibilityScope'], unique=False)

    op.create_table('gamePlayerLibraries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gamePlayerId', sa.BigInteger(), nullable=False),
    sa.Column('zoneScope', sa.Text(), nullable=False),
    sa.Column('orderedCardInstanceIds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gamePlayerId'], ['mtgGames.gamePlayers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgGames'
    )
    with op.batch_alter_table('gamePlayerLibraries', schema='mtgGames') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgGames_gamePlayerLibraries_gamePlayerId'), ['gamePlayerId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_gamePlayerLibraries_zoneScope'), ['zoneScope'], unique=False)

    op.create_table('printingImages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('printingId', sa.BigInteger(), nullable=False),
    sa.Column('faceName', sa.Text(), nullable=False),
    sa.Column('imageSize', sa.Text(), nullable=False),
    sa.Column('localPath', sa.Text(), nullable=True),
    sa.Column('publicUrl', sa.Text(), nullable=True),
    sa.Column('sourceUrl', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('contentType', sa.Text(), nullable=True),
    sa.Column('fileBytes', sa.BigInteger(), nullable=True),
    sa.Column('lastError', sa.Text(), nullable=True),
    sa.Column('lastAttemptedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downloadedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['printingId'], ['mtgCore.printings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printingId', 'faceName', 'imageSize', name='uq_printingImages_printing_face_size'),
    schema='mtgCore'
    )
    with op.batch_alter_table('printingImages', schema='mtgCore') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgCore_printingImages_faceName'), ['faceName'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_printingImages_imageSize'), ['imageSize'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_printingImages_printingId'), ['printingId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_printingImages_status'), ['status'], unique=False)
        batch_op.create_index('ix_printingImages_printingId_faceName_imageSize', ['printingId', 'faceName', 'imageSize'], unique=False)

    op.create_table('productContents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('productId', sa.BigInteger(), nullable=False),
    sa.Column('cardId', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('isCommander', sa.Boolean(), nullable=True),
    sa.Column('boardSection', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cardId'], ['mtgCore.cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productId'], ['mtgCore.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('productId', 'cardId', 'boardSection', name='uq_productContents_product_card_board'),
    schema='mtgCore'
    )
    with op.batch_alter_table('productContents', schema='mtgCore') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgCore_productContents_cardId'), ['cardId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgCore_productContents_productId'), ['productId'], unique=False)

    op.create_table('decks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('commanderCount', sa.Integer(), nullable=True),
    sa.Column('colorIdentity', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('ownerUserId', sa.BigInteger(), nullable=True),
    sa.Column('sourceType', sa.Text(), nullable=True),
    sa.Column('sourceProductId', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('isPublic', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sourceProductId'], ['mtgCore.products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgDecks'
    )
    with op.batch_alter_table('decks', schema='mtgDecks') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgDecks_decks_format'), ['format'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_decks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_decks_ownerUserId'), ['ownerUserId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_decks_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_mtgDecks_decks_sourceProductId'), ['sourceProductId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_decks_sourceType'), ['sourceType'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gameId', sa.BigInteger(), nullable=False),
    sa.Column('gamePlayerId', sa.BigInteger(), nullable=False),
    sa.Column('snapshotId', sa.BigInteger(), nullable=True),
    sa.Column('sequenceNumber', sa.BigInteger(), nullable=False),
    sa.Column('decisionType', sa.Text(), nullable=False),
    sa.Column('stateFeaturesJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('legalActionsJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chosenActionJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actionTakenEventId', sa.BigInteger(), nullable=True),
    sa.Column('decisionSource', sa.Text(), nullable=False),
    sa.Column('timeTakenMs', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actionTakenEventId'], ['mtgGames.events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gameId'], ['mtgGames.games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gamePlayerId'], ['mtgGames.gamePlayers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshotId'], ['mtgGames.stateSnapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgGames'
    )
    with op.batch_alter_table('decisions', schema='mtgGames') as batch_op:
        batch_op.create_index('ix_decisions_gameId_sequenceNumber', ['gameId', 'sequenceNumber'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_decisions_actionTakenEventId'), ['actionTakenEventId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_decisions_decisionSource'), ['decisionSource'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_decisions_decisionType'), ['decisionType'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_decisions_gameId'), ['gameId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_decisions_gamePlayerId'), ['gamePlayerId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_decisions_snapshotId'), ['snapshotId'], unique=False)

    op.create_table('deckCards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deckId', sa.BigInteger(), nullable=False),
    sa.Column('cardId', sa.BigInteger(), nullable=False),
    sa.Column('preferredPrintingId', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('boardType', sa.Text(), nullable=False),
    sa.Column('isCommander', sa.Boolean(), nullable=True),
    sa.Column('addedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cardId'], ['mtgCore.cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deckId'], ['mtgDecks.decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preferredPrintingId'], ['mtgCore.printings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deckId', 'cardId', 'boardType', name='uq_deckCards_deck_card_board'),
    schema='mtgDecks'
    )
    with op.batch_alter_table('deckCards', schema='mtgDecks') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckCards_boardType'), ['boardType'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckCards_cardId'), ['cardId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckCards_deckId'), ['deckId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckCards_preferredPrintingId'), ['preferredPrintingId'], unique=False)

    op.create_table('deckImports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deckId', sa.BigInteger(), nullable=False),
    sa.Column('importSource', sa.Text(), nullable=True),
    sa.Column('originalPayload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('importedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deckId'], ['mtgDecks.decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgDecks'
    )
    with op.batch_alter_table('deckImports', schema='mtgDecks') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckImports_deckId'), ['deckId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckImports_importSource'), ['importSource'], unique=False)

    op.create_table('deckTags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deckId', sa.BigInteger(), nullable=False),
    sa.Column('tagType', sa.Text(), nullable=False),
    sa.Column('tagValue', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deckId'], ['mtgDecks.decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgDecks'
    )
    with op.batch_alter_table('deckTags', schema='mtgDecks') as batch_op:
        batch_op.create_index('ix_deckTags_deckId_tagType_tagValue', ['deckId', 'tagType', 'tagValue'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckTags_deckId'), ['deckId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckTags_tagType'), ['tagType'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckTags_tagValue'), ['tagValue'], unique=False)

    op.create_table('deckVersions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deckId', sa.BigInteger(), nullable=False),
    sa.Column('versionNumber', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('changeSummary', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deckId'], ['mtgDecks.decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deckId', 'versionNumber', name='uq_deckVersions_deck_version'),
    schema='mtgDecks'
    )
    with op.batch_alter_table('deckVersions', schema='mtgDecks') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckVersions_deckId'), ['deckId'], unique=False)

    op.create_table('deckSnapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deckId', sa.BigInteger(), nullable=False),
    sa.Column('deckVersionId', sa.BigInteger(), nullable=True),
    sa.Column('summaryJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deckId'], ['mtgDecks.decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deckVersionId'], ['mtgDecks.deckVersions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgAnalysis'
    )
    with op.batch_alter_table('deckSnapshots', schema='mtgAnalysis') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_deckSnapshots_deckId'), ['deckId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_deckSnapshots_deckVersionId'), ['deckVersionId'], unique=False)

    op.create_table('simulationRuns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deckId', sa.BigInteger(), nullable=False),
    sa.Column('deckVersionId', sa.BigInteger(), nullable=True),
    sa.Column('runType', sa.Text(), nullable=False),
    sa.Column('opponentProfile', sa.Text(), nullable=True),
    sa.Column('simulationCount', sa.Integer(), nullable=False),
    sa.Column('configJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resultSummaryJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deckId'], ['mtgDecks.decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deckVersionId'], ['mtgDecks.deckVersions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgAnalysis'
    )
    with op.batch_alter_table('simulationRuns', schema='mtgAnalysis') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_simulationRuns_deckId'), ['deckId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_simulationRuns_deckVersionId'), ['deckVersionId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_simulationRuns_opponentProfile'), ['opponentProfile'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_simulationRuns_runType'), ['runType'], unique=False)

    op.create_table('deckVersionCards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deckVersionId', sa.BigInteger(), nullable=False),
    sa.Column('cardId', sa.BigInteger(), nullable=False),
    sa.Column('preferredPrintingId', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('boardType', sa.Text(), nullable=False),
    sa.Column('isCommander', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cardId'], ['mtgCore.cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deckVersionId'], ['mtgDecks.deckVersions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preferredPrintingId'], ['mtgCore.printings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deckVersionId', 'cardId', 'boardType', name='uq_deckVersionCards_version_card_board'),
    schema='mtgDecks'
    )
    with op.batch_alter_table('deckVersionCards', schema='mtgDecks') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckVersionCards_cardId'), ['cardId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckVersionCards_deckVersionId'), ['deckVersionId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgDecks_deckVersionCards_preferredPrintingId'), ['preferredPrintingId'], unique=False)

    op.create_table('cardInstances',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gameId', sa.BigInteger(), nullable=False),
    sa.Column('gamePlayerId', sa.BigInteger(), nullable=True),
    sa.Column('cardId', sa.BigInteger(), nullable=True),
    sa.Column('printingId', sa.BigInteger(), nullable=True),
    sa.Column('sourceDeckCardId', sa.BigInteger(), nullable=True),
    sa.Column('instanceType', sa.Text(), nullable=False),
    sa.Column('createdByEventId', sa.BigInteger(), nullable=True),
    sa.Column('zone', sa.Text(), nullable=False),
    sa.Column('zoneIndex', sa.Integer(), nullable=True),
    sa.Column('isTapped', sa.Boolean(), nullable=False),
    sa.Column('rotationDeg', sa.Integer(), nullable=False),
    sa.Column('isFaceDown', sa.Boolean(), nullable=False),
    sa.Column('displayFace', sa.Text(), nullable=True),
    sa.Column('battlefieldX', sa.Numeric(), nullable=True),
    sa.Column('battlefieldY', sa.Numeric(), nullable=True),
    sa.Column('stackIndex', sa.Integer(), nullable=True),
    sa.Column('metadataJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cardId'], ['mtgCore.cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['createdByEventId'], ['mtgGames.events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gameId'], ['mtgGames.games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gamePlayerId'], ['mtgGames.gamePlayers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['printingId'], ['mtgCore.printings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sourceDeckCardId'], ['mtgDecks.deckCards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgGames'
    )
    with op.batch_alter_table('cardInstances', schema='mtgGames') as batch_op:
        batch_op.create_index(batch_op.f('ix_mtgGames_cardInstances_cardId'), ['cardId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_cardInstances_createdByEventId'), ['createdByEventId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_cardInstances_gameId'), ['gameId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_cardInstances_gamePlayerId'), ['gamePlayerId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_cardInstances_instanceType'), ['instanceType'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_cardInstances_printingId'), ['printingId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_cardInstances_sourceDeckCardId'), ['sourceDeckCardId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgGames_cardInstances_zone'), ['zone'], unique=False)

    op.create_table('deckMatchupProfiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deckSnapshotId', sa.BigInteger(), nullable=False),
    sa.Column('archetypeName', sa.Text(), nullable=False),
    sa.Column('strengthScore', sa.Numeric(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deckSnapshotId'], ['mtgAnalysis.deckSnapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgAnalysis'
    )
    with op.batch_alter_table('deckMatchupProfiles', schema='mtgAnalysis') as batch_op:
        batch_op.create_index('ix_deckMatchupProfiles_snapshot_archetype', ['deckSnapshotId', 'archetypeName'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_deckMatchupProfiles_archetypeName'), ['archetypeName'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_deckMatchupProfiles_deckSnapshotId'), ['deckSnapshotId'], unique=False)

    op.create_table('deckMetrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('deckSnapshotId', sa.BigInteger(), nullable=False),
    sa.Column('metricGroup', sa.Text(), nullable=True),
    sa.Column('metricName', sa.Text(), nullable=False),
    sa.Column('metricValueNumeric', sa.Numeric(), nullable=True),
    sa.Column('metricValueText', sa.Text(), nullable=True),
    sa.Column('metricValueJson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deckSnapshotId'], ['mtgAnalysis.deckSnapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='mtgAnalysis'
    )
    with op.batch_alter_table('deckMetrics', schema='mtgAnalysis') as batch_op:
        batch_op.create_index('ix_deckMetrics_snapshot_metricName', ['deckSnapshotId', 'metricName'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_deckMetrics_deckSnapshotId'), ['deckSnapshotId'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_deckMetrics_metricGroup'), ['metricGroup'], unique=False)
        batch_op.create_index(batch_op.f('ix_mtgAnalysis_deckMetrics_metricName'), ['metricName'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deckMetrics', schema='mtgAnalysis') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_deckMetrics_metricName'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_deckMetrics_metricGroup'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_deckMetrics_deckSnapshotId'))
        batch_op.drop_index('ix_deckMetrics_snapshot_metricName')

    op.drop_table('deckMetrics', schema='mtgAnalysis')
    with op.batch_alter_table('deckMatchupProfiles', schema='mtgAnalysis') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_deckMatchupProfiles_deckSnapshotId'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_deckMatchupProfiles_archetypeName'))
        batch_op.drop_index('ix_deckMatchupProfiles_snapshot_archetype')

    op.drop_table('deckMatchupProfiles', schema='mtgAnalysis')
    with op.batch_alter_table('cardInstances', schema='mtgGames') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgGames_cardInstances_zone'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_cardInstances_sourceDeckCardId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_cardInstances_printingId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_cardInstances_instanceType'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_cardInstances_gamePlayerId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_cardInstances_gameId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_cardInstances_createdByEventId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_cardInstances_cardId'))

    op.drop_table('cardInstances', schema='mtgGames')
    with op.batch_alter_table('deckVersionCards', schema='mtgDecks') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckVersionCards_preferredPrintingId'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckVersionCards_deckVersionId'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckVersionCards_cardId'))

    op.drop_table('deckVersionCards', schema='mtgDecks')
    with op.batch_alter_table('simulationRuns', schema='mtgAnalysis') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_simulationRuns_runType'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_simulationRuns_opponentProfile'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_simulationRuns_deckVersionId'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_simulationRuns_deckId'))

    op.drop_table('simulationRuns', schema='mtgAnalysis')
    with op.batch_alter_table('deckSnapshots', schema='mtgAnalysis') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_deckSnapshots_deckVersionId'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_deckSnapshots_deckId'))

    op.drop_table('deckSnapshots', schema='mtgAnalysis')
    with op.batch_alter_table('deckVersions', schema='mtgDecks') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckVersions_deckId'))

    op.drop_table('deckVersions', schema='mtgDecks')
    with op.batch_alter_table('deckTags', schema='mtgDecks') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckTags_tagValue'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckTags_tagType'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckTags_deckId'))
        batch_op.drop_index('ix_deckTags_deckId_tagType_tagValue')

    op.drop_table('deckTags', schema='mtgDecks')
    with op.batch_alter_table('deckImports', schema='mtgDecks') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckImports_importSource'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckImports_deckId'))

    op.drop_table('deckImports', schema='mtgDecks')
    with op.batch_alter_table('deckCards', schema='mtgDecks') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckCards_preferredPrintingId'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckCards_deckId'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckCards_cardId'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_deckCards_boardType'))

    op.drop_table('deckCards', schema='mtgDecks')
    with op.batch_alter_table('decisions', schema='mtgGames') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgGames_decisions_snapshotId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_decisions_gamePlayerId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_decisions_gameId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_decisions_decisionType'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_decisions_decisionSource'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_decisions_actionTakenEventId'))
        batch_op.drop_index('ix_decisions_gameId_sequenceNumber')

    op.drop_table('decisions', schema='mtgGames')
    with op.batch_alter_table('decks', schema='mtgDecks') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgDecks_decks_sourceType'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_decks_sourceProductId'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_decks_slug'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_decks_ownerUserId'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_decks_name'))
        batch_op.drop_index(batch_op.f('ix_mtgDecks_decks_format'))

    op.drop_table('decks', schema='mtgDecks')
    with op.batch_alter_table('productContents', schema='mtgCore') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgCore_productContents_productId'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_productContents_cardId'))

    op.drop_table('productContents', schema='mtgCore')
    with op.batch_alter_table('printingImages', schema='mtgCore') as batch_op:
        batch_op.drop_index('ix_printingImages_printingId_faceName_imageSize')
        batch_op.drop_index(batch_op.f('ix_mtgCore_printingImages_status'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_printingImages_printingId'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_printingImages_imageSize'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_printingImages_faceName'))

    op.drop_table('printingImages', schema='mtgCore')
    with op.batch_alter_table('gamePlayerLibraries', schema='mtgGames') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgGames_gamePlayerLibraries_zoneScope'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_gamePlayerLibraries_gamePlayerId'))

    op.drop_table('gamePlayerLibraries', schema='mtgGames')
    with op.batch_alter_table('events', schema='mtgGames') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgGames_events_visibilityScope'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_events_turnNumber'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_events_step'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_events_phase'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_events_gameId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_events_eventType'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_events_actingGamePlayerId'))

    op.drop_table('events', schema='mtgGames')
    with op.batch_alter_table('branches', schema='mtgGames') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgGames_branches_parentSnapshotId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_branches_parentGameId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_branches_createdByUserId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_branches_childGameId'))

    op.drop_table('branches', schema='mtgGames')
    with op.batch_alter_table('products', schema='mtgCore') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgCore_products_setId'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_products_productType'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_products_productCode'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_products_name'))

    op.drop_table('products', schema='mtgCore')
    with op.batch_alter_table('printings', schema='mtgCore') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgCore_printings_uuid'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_printings_setId'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_printings_rarity'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_printings_cardId'))

    op.drop_table('printings', schema='mtgCore')
    with op.batch_alter_table('cardFaces', schema='mtgCore') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgCore_cardFaces_cardId'))

    op.drop_table('cardFaces', schema='mtgCore')
    with op.batch_alter_table('cardRoleTags', schema='mtgAnalysis') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_cardRoleTags_source'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_cardRoleTags_roleValue'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_cardRoleTags_roleType'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_cardRoleTags_cardId'))
        batch_op.drop_index('ix_cardRoleTags_cardId_roleType_roleValue')

    op.drop_table('cardRoleTags', schema='mtgAnalysis')
    with op.batch_alter_table('cardMatchupTags', schema='mtgAnalysis') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_cardMatchupTags_targetTag'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_cardMatchupTags_source'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_cardMatchupTags_relationType'))
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_cardMatchupTags_cardId'))
        batch_op.drop_index('ix_cardMatchupTags_cardId_relationType_targetTag')

    op.drop_table('cardMatchupTags', schema='mtgAnalysis')
    with op.batch_alter_table('stateSnapshots', schema='mtgGames') as batch_op:
        batch_op.drop_index('ix_stateSnapshots_gameId_sequenceNumber')
        batch_op.drop_index(batch_op.f('ix_mtgGames_stateSnapshots_turnNumber'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_stateSnapshots_snapshotHash'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_stateSnapshots_phase'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_stateSnapshots_gameId'))

    op.drop_table('stateSnapshots', schema='mtgGames')
    with op.batch_alter_table('games', schema='mtgGames') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgGames_games_winnerGamePlayerId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_games_status'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_games_rootGameId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_games_parentSnapshotId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_games_parentGameId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_games_gameMode'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_games_format'))

    op.drop_table('games', schema='mtgGames')
    with op.batch_alter_table('gamePlayers', schema='mtgGames') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgGames_gamePlayers_userId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_gamePlayers_result'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_gamePlayers_playerType'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_gamePlayers_gameId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_gamePlayers_deckVersionId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_gamePlayers_deckId'))
        batch_op.drop_index(batch_op.f('ix_mtgGames_gamePlayers_aiProfile'))

    op.drop_table('gamePlayers', schema='mtgGames')
    with op.batch_alter_table('sets', schema='mtgCore') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgCore_sets_setType'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_sets_name'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_sets_code'))

    op.drop_table('sets', schema='mtgCore')
    with op.batch_alter_table('cards', schema='mtgCore') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgCore_cards_uuid'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_cards_oracleId'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_cards_normalizedName'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_cards_name'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_cards_manaValue'))
        batch_op.drop_index(batch_op.f('ix_mtgCore_cards_defaultSetCode'))

    op.drop_table('cards', schema='mtgCore')
    with op.batch_alter_table('archetypes', schema='mtgAnalysis') as batch_op:
        batch_op.drop_index(batch_op.f('ix_mtgAnalysis_archetypes_name'))

    op.drop_table('archetypes', schema='mtgAnalysis')
    # ### end Alembic commands ###
